### ISSUE TITLE
migrate into core monorepo?

### ISSUE THREAD

**Issue by ianstormtaylor** [GitbookIO/slate-sugar#6]
Hey @Zhouzi and @Soreine, first of all just wanted to say this library is an absolutely genius idea. It feels so good to be defining documents this way.

I'm in the process of converting all of the core Slate tests to use the JSX syntax right now, because I  think it will make them 100x easier to write and reason about. As I was doing it, I realized that the current one is slightly out-of-date with the creation logic. And I also noticed that there's a weird dependency management problem of using `slate-sugar` inside Slate because it relies on a peer dep of `slate` itself... so I ended up having to copy/paste the `dist` for now.

But... it got me wondering. Would you be opposed to having the hyperscript helper maintained as part of core? One of the next things I'm doing is converting Slate's repo to use lerna, and I think I want to have one of the packages be a hyperscript helper. One because it would get maintained along with the other models, for easier migrations. Two because it's going to be used in all of the other core repos for testing. And three because I think it might be nice to make it even more prominent for other users.

Anyways, wanted to run the idea by you. I'm still working on the conversion, but I'll probably start the monorepo process very soon. Thanks!

**Comment by Zhouzi** [comment]
Hey @ianstormtaylor, glad you like `slate-sugar`, it has been quite useful for us as well so far 😄 

Moving it to the core repository makes total sense 👍 

From what I've read in [ianstormtaylor/slate#1092](https://github.com/ianstormtaylor/slate/issues/1092), it's probably missing a few things that should be straightforward to implement. And as you said, it's not up to date with the latest version of slate itself.

Anyway, let us know if we can help with the migration 💪 

Related PR: [ianstormtaylor/slate#1106](https://github.com/ianstormtaylor/slate/pull/1106)

**Comment by ianstormtaylor** [comment]
Thanks @Zhouzi! I will definitely let you know if I have any questions as I'm converting. Thanks again for this idea!
